catalog/urls.py
from django.urls import path

from .views import CatalogView, ProductListView, ProductDetailView, CommentDeleteView, CommentEditView, FavoritesAddUserView, SearchProductListView, DynamicFiltersProducts

from django.contrib.auth.decorators import login_required

from django.views.decorators.cache import cache_page


urlpatterns = [
    path('', cache_page(60*2)(CatalogView.as_view()), name='catalog'),
    path('dynamic-filters/', DynamicFiltersProducts.as_view(), name='dynamic-filters'),
    path('search/', SearchProductListView.as_view(), name='search'),
    path('<slug:category_slug>/', ProductListView.as_view(), name='product_list'),
    path('<slug:category_slug>/<slug:product_slug>/', cache_page(60*2)(ProductDetailView.as_view()), name='product_detail'),

    path('delete_comment/<int:comment_id>', CommentDeleteView.as_view(), name='delete_comment'),
    path('edit_comment/<int:comment_id>', CommentEditView.as_view(), name='edit_comment'),

    path('add_favorites/<int:product_id>', login_required(FavoritesAddUserView.as_view()), name='add_favorites'),
]

core/urls.py
from django.urls import path
from .views import IndexView, AboutView, DeliveryView, RefundView, ContactsView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('refund/', RefundView.as_view(), name='refund'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
]

yumezo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    
    path('', include('core.urls')),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('users.urls')),
]


'''
    Отображение медиа файлов в режиме тестирования приложения (DEBUG = True)
'''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from users.models import User
from django.db.models import Avg


'''
    Модель описывающая категории товаров (прим. "Манга", "Одежда и аксессуары", "Фигурки")
'''
class Category(models.Model):
    name = models.CharField(verbose_name='Наименование категории', max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True, db_index=True, editable=False)
    image = models.ImageField(verbose_name='Изображение категории', upload_to='icons_categories')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    '''
        Переопределение метода сохранения записи.
        С помощью библиотеки pytils переводим киррилицу в латиницу по полю name.
        В поле slug записывается поле name на латинице.
    '''
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product_list', kwargs={"category_slug": self.slug})

    def __str__(self):
        return self.name
    

'''
    Модель описывающая жанры товаров (прим. "Боевик", "Драма", "Фэнтези")
'''
class Genre(models.Model):
    name = models.CharField(verbose_name='Наименование жанра', max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True, db_index=True, editable=False)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    '''
        Переопределение метода сохранения записи.
        С помощью библиотеки pytils переводим киррилицу в латиницу по полю name.
        В поле slug записывается поле name на латинице.
    '''
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    

'''
    Модель описывающая источник товаров (прим. "Naruto", "Bleach", "Death Note")
'''
class Source(models.Model):
    name = models.CharField(verbose_name='Наименование источника', max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True, db_index=True, editable=False)

    class Meta:
        verbose_name = 'Источник'
        verbose_name_plural = 'Источники'

    '''
        Переопределение метода сохранения записи.
        С помощью библиотеки pytils переводим киррилицу в латиницу по полю name.
        В поле slug записывается поле name на латинице.
    '''
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    

'''
    Модель описывающая базовые характеристики товаров, которые встречаются у всех (прим. "Наименование", "Источник", "Цена")
'''
class Product(models.Model):
    name = models.CharField(verbose_name='Наименование товара', max_length=128)
    name_eng = models.CharField(verbose_name='Наименование товара (англ.)', max_length=128)
    slug = models.SlugField(max_length=128, unique=True, db_index=True, editable=False)
    category = models.ForeignKey(verbose_name='Категория', to=Category, on_delete=models.CASCADE)
    source = models.ForeignKey(verbose_name='Источник', to=Source, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name='Изображение продукта', upload_to='icons_products')
    description = models.TextField(verbose_name='Описание товара')
    price = models.PositiveIntegerField(verbose_name='Цена', help_text='Цена указывается в рублях (руб.)')
    discount = models.PositiveIntegerField(verbose_name='Скидка', default=0, help_text='Скидка указывается в процентах (%)')
    is_active = models.BooleanField(verbose_name='Активный продукт', default=False)
    count_sales = models.PositiveIntegerField(verbose_name='Количество продаж', default=0, editable=False)
    rating = models.SmallIntegerField(verbose_name='Средний рейтинг товара', default=0, editable=False)

    class Meta:
        verbose_name = 'Базовый продукт'
        verbose_name_plural = 'Базовые продукты'

    '''
        Переопределение метода сохранения записи.
        С помощью библиотеки pytils переводим киррилицу в латиницу по полю name.
        Авто-слаг, при добавлении в конец слага добавляется id.
    '''
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.name) + '-' + str(self.pk)
            super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product_detail', kwargs={"category_slug": self.category.slug, "product_slug": self.slug})
    
    # Метод преобразования цены с учетом скидки, если она есть
    def price_discount(self):
        if self.discount:
            return int(self.price + ((self.price * self.discount) / 100))
        
        return self.price
    

    # Метод рассчета рейтинга
    def update_rating(self):
        average_grade = Comment.objects.filter(product__slug=self.slug).aggregate(avg_grade=Avg('grade'))['avg_grade']
        
        if average_grade is None:
            self.rating = 0
        else:
            self.rating = average_grade
            
        self.save()

'''
    Модель описывающая специфические для разных категорий характеристики товаров (прим. "Вес", "Размер", "Длина")
'''
class Property(models.Model):
    name = models.CharField(verbose_name='Наименование характеристики', max_length=128)

    class Meta:
        verbose_name = 'Характеристика продукта'
        verbose_name_plural = 'Характеристики продуктов'

    def __str__(self):
        return self.name
    

'''
    Модель описывающая значение для спец. характеристики продукта (прим. "Вес - 100 гр.", "Размер - XL", "Длина - 20 см.")
'''
class ProductProperty(models.Model):
    product = models.ForeignKey(verbose_name='Продукт', to=Product, on_delete=models.CASCADE)
    property = models.ForeignKey(verbose_name='Характеристика', to=Property, on_delete=models.CASCADE)
    value_string = models.CharField(verbose_name='Текстовое значение характеристики', max_length=250, null=True, blank=True, help_text='Значение задается текстом')
    value_integer = models.IntegerField(verbose_name='Числовое значение характеристики', null=True, blank=True, help_text='Значение задается целым числом')
    value_genres = models.ManyToManyField(verbose_name='Жанры', to=Genre, null=True, blank=True, help_text='Поле для категорий, в которых есть поле - жанры')

    class Meta:
        verbose_name = 'Сопоставление характеристик продуктов'
        verbose_name_plural = 'Сопоставление характеристик продуктов'

    def __str__(self):
        return f'{self.product.name} | {self.property.name}'
    

'''
    Модель описывающая комментарии пользователей
'''
class Comment(models.Model):
    product = models.ForeignKey(verbose_name='Продукт', to=Product, on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='Пользователь', to=User, on_delete=models.CASCADE)
    review_text = models.TextField(verbose_name='Текст комментария')
    create_date = models.DateTimeField(verbose_name='Дата создания комментария', auto_now_add=True)
    grade = models.SmallIntegerField(verbose_name='Оценка пользователя')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.product.name} | {self.user.username}'
    

'''
    Модель описывающая избранное пользователей
'''
class Favorites(models.Model):
    product = models.ForeignKey(verbose_name='Продукт', to=Product, on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='Пользователь', to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} | {self.product.name}'

    def get_absolute_url(self):
        return reverse('delete_favorites', kwargs={"favorites_id": self.pk})

    class Meta:
        verbose_name = 'Избранное пользователя'
        verbose_name_plural = 'Избранное пользователей'


'''
    Модель описывающая корзину пользователя
'''
class Cart(models.Model):
    product = models.ForeignKey(verbose_name='Продукт', to=Product, on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='Пользователь', to=User, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(verbose_name='Количество', default=1)

    def __str__(self):
        return f'{self.user.username} | {self.product.name} | {self.amount}'
    
    def total_price_not_sale(self):
        return self.amount * self.product.price
    
    def total_price_sale(self):
        return self.amount * self.product.price_discount()

    class Meta:
        verbose_name = 'Корзина пользователя'
        verbose_name_plural = 'Корзины пользователей'


'''
    Модель описывающая заказ пользователя
'''
class Order(models.Model):
    class Status(models.TextChoices):
        CR = 'CR', 'Создан'
        DEL = 'DEL', 'В доставке'
        CONF_DEL = 'CONF_DEL', 'Доставлен'
        REC = 'REC', 'Получен'

    user = models.ForeignKey(verbose_name='Пользователь', to=User, on_delete=models.CASCADE)
    products = models.ManyToManyField(verbose_name='Продукты для заказа', to=Product)
    city = models.CharField(verbose_name='Город / Населенный пункт', max_length=255)
    street = models.CharField(verbose_name='Улица', max_length=255)
    house = models.PositiveSmallIntegerField(verbose_name='Дом / корпус')
    apart = models.PositiveSmallIntegerField(verbose_name='Квартира')
    postcode = models.IntegerField(verbose_name='Почтовый индекс')
    create_date = models.DateField(auto_now_add=True, db_index=True)
    total_price = models.PositiveIntegerField('Общая стоимость заказа', default=0)
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    status = models.CharField(verbose_name='Статус заказа', choices=Status.choices, default=Status.CR)

    def __str__(self):

catalog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comment
        
class AddNewCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['review_text', 'grade']

class EditCommentForm(ModelForm):
    review_text = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'product-detail-reviews-textarea',
        'placeholder': 'Оставьте комментарий...',
    }), label=None)

    class Meta:
        model = Comment
        fields = ['review_text', 'grade']

catalog/templates/catalog/catalog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="catalog-list-main-row-link">
        <a class="catalog-list-main-row-link-item" href="{% url 'index' %}">Главная</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{% url 'catalog' %}">Каталог</a>
    </div>
    <h1 class="catalog-list-main-title">Каталог</h1>
    <div class="catalog-list-main-categories">
        {% for category in categories %}
        <div class="catalog-list-main-categories-item">
            <a href="{{ category.get_absolute_url }}">
                <img class="catalog-list-main-categories-item-img" src="{{ category.image.url }}" alt="{{ category.name }}">
            </a>
            <a class="catalog-list-main-categories-item-text" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

catalog/templates/catalog/product-detail.html
{% extends "base.html" %}
{% load static %}
{% load range_values %}
{% load review_declination %}

{% block content %}
    <div class="catalog-list-main-row-link">
        <a class="catalog-list-main-row-link-item" href="{% url 'index' %}">Главная</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{% url 'catalog' %}">Каталог</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
    </div>
    <h2 class="product-detail-title">{{ product.name }}</h2>
    <div class="product-detail-stars">
        <div class="product-detail-stars-row">
            <div class="rating-result">
                {% for _ in product.rating|range_values_star %}
                    <span class="active"></span>
                {% endfor %}
                {% for _ in product.rating|range_values_no_star %}
                    <span></span>
                {% endfor %}
            </div>
            <a class="product-detail-stars-row-link" href="#review">{{ count_reviews }} {{ count_reviews|review_declination }}</a>
        </div>
        <div class="product-detail-stars-forever">
            {% if not user.is_authenticated %}  
                <img id='forever' src="{% static 'img/icons/icon-love.png' %}" alt="Forever">
                <a href="{% url 'login' %}" class="product-detail-stars-forever-link-not-ajax">В избранное</a>
            {% else %}
                {% if not is_favorites %}
                    <img id='forever' src="{% static 'img/icons/icon-love.png' %}" alt="Forever">
                    <a href="{% url 'add_favorites' product_id=product.pk %}" class="product-detail-stars-forever-link">В избранное</a>
                {% else %}
                    <img id='forever' src="{% static 'img/icons/heart-red.png' %}" alt="Forever">
                    <a href="{% url 'add_favorites' product_id=product.pk %}" class="product-detail-stars-forever-link-red">В избранном</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="product-detail-main">
        <div class="product-detail-main-left">
            <img class="product-detail-main-left-img" src="{{ product.image.url }}" alt="Poster">
            <div class="product-detail-main-left-text">
                    <h2 class="product-detail-main-left-text-engtitle">{{ product.name_eng }}</h2>
                    <p class="product-detail-main-left-text-p">Категория: <a class="product-detail-main-left-text-link" href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></p>
                    <p class="product-detail-main-left-text-p">Источник: <a class="product-detail-main-left-text-link" href="#">{{ product.source.name }}</a></p>
                    {% for property in proretries %}
                        <p class="product-detail-main-left-text-p">{{ property.property.name }}: {% if property.value_string %} {{ property.value_string }} {% elif property.value_integer %} {{ property.value_integer }} {% else %} {% for genre in property.value_genres.all %} <a class="product-detail-main-left-text-link" href="#">{{ genre.name }}</a> {% if not forloop.last %},{% endif %} {% endfor %} {% endif %}</p>
                    {% endfor %}
            </div>
        </div>
        <div class="product-detail-main-right">
            {% if product.discount %}
                <p class="product-detail-main-right-orig">Оригинальная цена</p>
                <p class="product-detail-main-right-orig-price">{{product.price_discount }} ₽</p>
                <p class="product-detail-main-right-orig">Специальная цена</p>
                <p class="product-detail-main-right-spec-price">{{product.price }} ₽</p>
            {% else %}
                <p class="product-detail-main-right-orig">Оригинальная цена</p>
                <p class="product-detail-main-right-spec-price">{{product.price }} ₽</p>
            {% endif %}
            {% if product.pk in current_user_cart %}
                    <a class="product-detail-main-right-btn-green" href="{% url 'cart' %}">В корзине</a>
            {% elif user.is_active %}
                    <a class="product-detail-main-right-btn" href="{% url 'cart_add' product_id=product.pk %}">В корзину</a>
            {% else %}
                    <a class="product-detail-main-right-btn-no-ajax" href="{% url 'activate_email_done' %}">В корзину</a>
            {% endif %}
            {% if product.category.slug == 'odezhda' %}
            <div class="product-detail-clothers-size">
                <div class="product-detail-clothers-size-top">
                    <p class="product-detail-clothers-size-pole">Пол</p>
                    <select class="product-detail-clothers-size-pole-select" name="" id="">
                        <option selected disabled hidden>-</option>
                        <option value="">М</option>
                        <option value="">Ж</option>
                    </select>
                </div>
                <div class="product-detail-clothers-size-bottom">
                    <p class="product-detail-clothers-size-pole">Размер</p>
                    <select class="product-detail-clothers-size-size-select" name="" id="">
                        <option selected disabled hidden>-</option>
                        <option value="">S</option>
                        <option value="">M</option>
                        <option value="">L</option>
                        <option value="">XL</option>
                        <option value="">XXL</option>
                    </select>
                </div>
            </div>
            <a onclick="openPopup()" class="product-detail-sizes-table">Таблица размеров</a>
            {% endif %}
        </div>
    </div>
    <div class="product-detail-desc">
        <h2 class="product-detail-desc-h">Описание</h2>
        <p class="product-detail-desc-text">{{ product.description }}</p>
    </div>
    <div class="product-detail-reviews">
        <h2 id="review" class="product-detail-reviews-h">Отзывы</h2>
        {% if user.is_authenticated and user.is_active %}
            {% if not is_user_comment %}
                <form method="POST">
                    {% csrf_token %}
                    <textarea class="product-detail-reviews-textarea" placeholder="Оставьте комментарий..." name="review_text" id="id_review_text"></textarea>
                    {% for error in form.review_text.errors %}
                        <p class="product-detail-reviews-error">* {{ error }} </p>
                    {% endfor %}
                    <div class="product-detail-reviews-row">
                        <div class="product-detail-reviews-stars">
                            <p>Ваша оценка:</p>
                            <div class="rating-area">
                                <input type="radio" id="id_grade_five" name="grade" value="5">
                                <label for="id_grade_five" title="Оценка «5»"></label>	
                                <input type="radio" id="id_grade_four" name="grade" value="4">
                                <label for="id_grade_four" title="Оценка «4»"></label>    
                                <input type="radio" id="id_grade_three" name="grade" value="3">
                                <label for="id_grade_three" title="Оценка «3»"></label>  
                                <input type="radio" id="id_grade_two" name="grade" value="2">
                                <label for="id_grade_two" title="Оценка «2»"></label>    
                                <input type="radio" id="id_grade_one" name="grade" value="1">
                                <label for="id_grade_one" title="Оценка «1»"></label>
                            </div>
                        </div>
                        <button type="submit" class="product-detail-reviews-link">Отправить</a>
                    </div>
                    {% for error in form.grade.errors %}
                        <p class="product-detail-reviews-error">*{{ error }} </p>
                    {% endfor %}
                </form>

                <div class="product-detail-reviews-line"></div>
            {% endif %}
        {% endif %}
        {% for comment in comments %}
            <div class="product-detail-reviews-item">
                <span class="circle-img-product">
                    {% if comment.user.profile_image %}
                        <img class="profile-row-links-img" src="{{ comment.user.profile_image.url }}" alt="Profile Logo">
                    {% else %}
                        <img class="profile-row-links-img" src="{% static 'img/default.png' %}" alt="Profile Logo">
                    {% endif %}
                </span>
                <div class="product-detail-reviews-item-column">
                    <div class="product-detail-reviews-name">
                        <h1 class="product-detail-reviews-username">{{ comment.user.username }}</h1>
                        <p class="product-detail-reviews-date">{{ comment.create_date }}</p>
                        {% if comment.user == user %}
                            <form action="{% url 'edit_comment' comment_id=comment.pk %}">
                                <button type='submit' class="product-detail-edit">Редактировать</button>
                            </form>
                            <form action="{% url 'delete_comment' comment_id=comment.pk %}">
                                <button type='submit' class="product-detail-delete">Удалить</button>
                            </form>
                        {% endif %}
                    </div> 
                    <div class="rating-result">
                        {% for _ in comment.grade|range_values_star %}
                            <span class="active"></span>
                        {% endfor %}
                        {% for _ in comment.grade|range_values_no_star %}
                            <span></span>
                        {% endfor %}
                    </div>
                    <p class="product-detail-reviews-item-desc">{{ comment.review_text }}</p>
                </div> 
            </div>
        {% endfor %}
    </div>
{% endblock content %}

catalog/templates/catalog/product-list-search.html
{% extends "base.html" %}
{% load static %}
{% load product_count_declination %}

{% block content %}
<h1 class="catalog-list-main-title-search">По запросу "{{ search_value }}" найдено {{ count_products }} {{ count_products|product_count_declination }}</h1>

<div class="product-list-main-row">
    <div class="product-list-main-row-products">
        {% if products.exists %}
            <div class="product-list-main-row-products-search-grid">
                {% for product in products %}
                <div class="product-list-main-row-products-grid-item">
                    <a href="{{ product.get_absolute_url }}">
                        <img class="product-list-main-row-products-grid-item-img" src="{{ product.image.url }}" alt="Logo">
                        <a class="product-list-main-row-products-grid-item-name" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                        {% if product.discount %}
                            <div class="prices">
                                <p class="product-list-main-row-products-grid-item-price-sale">{{ product.price }} ₽</p>
                                <p class="product-list-main-row-products-grid-item-price-through">{{ product.price_discount }} ₽</p>
                            </div>
                        {% else %}
                            <p class="product-list-main-row-products-grid-item-price">{{ product.price }} ₽</p>
                        {% endif %}
                        {% if product.pk in current_user_cart %}
                            <a class="product-list-main-row-products-grid-item-btn-green" href="{% url 'cart' %}">В корзине</a>
                        {% elif user.is_active %}
                            <a class="product-list-main-row-products-grid-item-btn" href="{% url 'cart_add' product_id=product.pk %}">В корзину</a>
                        {% else %}
                            <a class="product-list-main-row-products-grid-item-btn-no-ajax" href="{% url 'activate_email_done' %}">В корзину</a>
                        {% endif %}
                    </a>
                </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="no-items-search">
                <p class="no-items-text">Не найдено ни одного товара, доступного для заказа</p>
            </div>
        {% endif %}
        
        {% if is_paginated %}
            <div class="product-list-main-pagination">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">«</a>
                {% endif %}
                
                {% for page in paginator.page_range %}
                    {% if page == page_obj.number %}
                        <a class="active" href="?page={{ page }}">{{ page }}</a>
                    {% else %}
                        <a href="?page={{ page }}">{{ page }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">»</a>
                {% endif %}
            </div>
        {% endif %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/filters.js' %}"></script>
{% endblock content %}

catalog/templates/catalog/review-edit.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="catalog-list-main-row-link">
        <a class="catalog-list-main-row-link-item" href="{% url 'index' %}">Главная</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{% url 'catalog' %}">Каталог</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{{ comment.product.category.get_absolute_url }}">{{ comment.product.category }}</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{{ comment.product.get_absolute_url }}">{{ comment.product.name }}</a>
        <p>-</p>
        <a class="catalog-list-main-row-link-item" href="{% url 'edit_comment' comment_id=comment.pk %}">Редактирование отзыва</a>
    </div>
    <h2 class="product-detail-title">Редактирование отзыва</h2>
    <br>
    <br>

    <form method="POST">
                    {% csrf_token %}

                    {{ form.review_text }}

                    {% for error in form.review_text.errors %}
                        <p class="product-detail-reviews-error">* {{ error }} </p>
                    {% endfor %}
                    
                    <div class="product-detail-reviews-row">
                        <div class="product-detail-reviews-stars">
                            <p>Ваша оценка:</p>
                            <div class="rating-area">

                                <script>
                                    document.addEventListener('DOMContentLoaded', function() {
                                        var gradeValue = "{{ comment.grade }}";
                                        var radioButton = document.getElementById('id_grade_' + gradeValue);
                                        radioButton.checked = true;
                                    });
                                </script>

                                <input type="radio" id="id_grade_5" name="grade" value="5">
                                <label for="id_grade_5" title="Оценка «5»"></label>	
                                <input type="radio" id="id_grade_4" name="grade" value="4">
                                <label for="id_grade_4" title="Оценка «4»"></label>     
                                <input type="radio" id="id_grade_3" name="grade" value="3">
                                <label for="id_grade_3" title="Оценка «3»"></label>  
                                <input type="radio" id="id_grade_2" name="grade" value="2">
                                <label for="id_grade_2" title="Оценка «2»"></label>    
                                <input type="radio" id="id_grade_1" name="grade" value="1">
                                <label for="id_grade_1" title="Оценка «1»"></label>
                            </div>
                        </div>
                        <button type="submit" class="product-detail-reviews-link">Отправить</a>
                    </div>
                    {% for error in form.grade.errors %}
                        <p class="product-detail-reviews-error">*{{ error }} </p>
                    {% endfor %}
                </form>
{% endblock content %}